# helper tools

services:
  imagor:
    image: docker-hub.sandstorm.de/docker-infrastructure/imagor:unreleased-pr621-mozjpeg
    #image: ghcr.io/cshum/imagor-mozjpeg:docker-variants@sha256:80637bfd1c5307364c8fca73bf8863a6d29fa06b1e7b9b67eb08962e7331c30e
    #build:
    #  context: ./imagor_docker
      # dockerfile: Dockerfile_00_default
      # dockerfile: Dockerfile_02_build_from_imagor_src
    env_file:
      - './imagor_docker/imagor.env'
    environment:
      DEBUG: 1

      TZ: 'Europe/Berlin'
      IMAGOR_AUTO_WEBP: 1

      FILE_SAFE_CHARS: --
      FILE_RESULT_STORAGE_EXPIRATION: 6h
      FILE_STORAGE_EXPIRATION: 6h

      VIPS_MOZJPEG: 1
    volumes:
      - imagor_cache:/mnt/imagor_cache
      - ./vendor/orchestra/testbench-core/laravel/storage:/app/storage
    ports:
      - 8001:8001


volumes:
  imagor_cache:
