# helper tools

services:
  imagor:
    build:
      context: ./imagor_docker
    env_file:
      - './imagor_docker/imagor.env'
    environment:
      TZ: 'Europe/Berlin'
      IMAGOR_AUTO_WEBP: 1
      FILE_RESULT_STORAGE_EXPIRATION: 6h
      FILE_STORAGE_EXPIRATION: 6h

      # TODO: working???
      VIPS_MOZJPEG: 1
    volumes:
      - imagor_cache:/mnt/imagor_cache
      - ./vendor/orchestra/testbench-core/laravel/storage:/app/storage
    ports:
      - 8001:8001


volumes:
  imagor_cache:
