# https://github.com/cshum/imagor/blob/master/Dockerfile
ARG GOLANG_VERSION=1.25.1
FROM golang:${GOLANG_VERSION}-trixie as builder

ARG VIPS_VERSION=8.17.2
ARG TARGETARCH
ARG ENABLE_MAGICK=false

ARG MOZJPEG_VERSION=4.1.1
ARG MOZJPEG_URL=https://github.com/mozilla/mozjpeg/archive


ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

ADD ${MOZJPEG_URL}/v${MOZJPEG_VERSION}.tar.gz /tmp/
WORKDIR /tmp


RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update && \
  apt-get install --no-install-recommends -y  build-essential libboost-all-dev pkg-config  autoconf automake libtool nasm make cmake flex

RUN DEBIAN_FRONTEND=noninteractive \
  apt-get install --no-install-recommends -y  libpng-tools libpng-dev zlib1g-dev

RUN tar xf v${MOZJPEG_VERSION}.tar.gz \
  && cd mozjpeg-${MOZJPEG_VERSION} \
  && cmake -G"Unix Makefiles" . \
  && make -j4 \
  && make install \
  && cp jpegint.h /usr/include/jpegint.h \
  && cd .. \
  && rm -rf mozjpeg


# Installs libvips + required libraries + conditionally ImageMagick
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update && \
  apt-get install --no-install-recommends -y \
  ca-certificates \
  automake build-essential curl \
  meson ninja-build pkg-config \
  gobject-introspection gtk-doc-tools libglib2.0-dev libjpeg62-turbo-dev libpng-dev \
  libwebp-dev libtiff-dev libexif-dev libxml2-dev libpoppler-glib-dev \
  swig libpango1.0-dev libmatio-dev libopenslide-dev libcfitsio-dev libopenjp2-7-dev liblcms2-dev \
  libgsf-1-dev libfftw3-dev liborc-0.4-dev librsvg2-dev libimagequant-dev libaom-dev \
  libspng-dev libcgif-dev libheif-dev libheif-plugin-x265 libheif-plugin-aomenc libjxl-dev libavif-dev && \
  if [ "$ENABLE_MAGICK" = "true" ]; then \
    apt-get install --no-install-recommends -y libmagickwand-dev; \
  fi && \
  cd /tmp && \
    export PKG_CONFIG_PATH=/opt/mozjpeg/lib64/pkgconfig/ && \
    curl -fsSLO https://github.com/libvips/libvips/releases/download/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.xz && \
    tar xf vips-${VIPS_VERSION}.tar.xz && \
    cd vips-${VIPS_VERSION} && \
    meson setup _build \
    --buildtype=release \
    --strip \
    --prefix=/usr/local \
    --libdir=lib \
    -Dmagick=$(if [ "$ENABLE_MAGICK" = "true" ]; then echo "enabled"; else echo "disabled"; fi) \
    -Djpeg-xl=enabled \
    -Dintrospection=disabled && \
    ninja -C _build && \
    ninja -C _build install && \
  ldconfig && \
  rm -rf /usr/local/lib/libvips-cpp.* && \
  rm -rf /usr/local/lib/*.a && \
  rm -rf /usr/local/lib/*.la

ENV PKG_CONFIG_PATH=/opt/mozjpeg/lib64/pkgconfig/ \
    LD_LIBRARY_PATH=/opt/mozjpeg/lib64

WORKDIR ${GOPATH}/src/github.com/cshum/imagor


RUN git clone https://github.com/cshum/imagor .
RUN go mod download


RUN go build -o ${GOPATH}/bin/imagor ./cmd/imagor/main.go

FROM debian:trixie-slim as runtime
LABEL maintainer="adrian@cshum.com"

ARG ENABLE_MAGICK=false

COPY --from=builder /usr/local/lib /usr/local/lib
COPY --from=builder /etc/ssl/certs /etc/ssl/certs
COPY --from=builder /opt/mozjpeg /opt/mozjpeg

ENV PKG_CONFIG_PATH=/opt/mozjpeg/lib64/pkgconfig/ \
    LD_LIBRARY_PATH=/opt/mozjpeg/lib64

# Install runtime dependencies including conditionally ImageMagick
RUN DEBIAN_FRONTEND=noninteractive \
  apt-get update && \
  apt-get install --no-install-recommends -y \
  procps curl libglib2.0-0 libjpeg62-turbo libpng16-16 libopenexr-3-1-30 \
  libwebp7 libwebpmux3 libwebpdemux2 libtiff6 libexif12 libxml2 libpoppler-glib8t64 \
  libpango-1.0-0 libmatio13 libopenslide0 libopenjp2-7 libjemalloc2 \
  libgsf-1-114 libfftw3-bin liborc-0.4-0 librsvg2-2 libcfitsio10t64 libimagequant0 libaom3 \
  libspng0 libcgif0 libheif1 libheif-plugin-x265 libheif-plugin-aomenc libjxl0.11 && \
  if [ "$ENABLE_MAGICK" = "true" ]; then \
    apt-get install --no-install-recommends -y libmagickwand-7.q16-10; \
  fi && \
  ln -s /usr/lib/$(uname -m)-linux-gnu/libjemalloc.so.2 /usr/local/lib/libjemalloc.so && \
  apt-get autoremove -y && \
  apt-get autoclean && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=builder /go/bin/imagor /usr/local/bin/imagor

ENV VIPS_WARNING=0
ENV MALLOC_ARENA_MAX=2
ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so

ENV PORT 8000

# use unprivileged user
USER nobody

ENTRYPOINT ["/usr/local/bin/imagor"]

EXPOSE ${PORT}






USER root

# Install xz-utils before extracting
RUN apt-get update && apt-get install -y xz-utils && rm -rf /var/lib/apt/lists/*

# add the s6 overlay
ARG S6_OVERLAY_VERSION=3.2.1.0
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz
ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz /tmp
RUN tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz

# add supercronic
ADD https://github.com/aptible/supercronic/releases/download/v0.2.34/supercronic-linux-amd64 /tmp
RUN echo "e8631edc1775000d119b70fd40339a7238eece14 /tmp/supercronic-linux-amd64" | sha1sum -c - && \
    chmod +x /tmp/supercronic-linux-amd64 && \
    mv /tmp/supercronic-linux-amd64 /usr/local/bin/supercronic

# Copy s6 service configurations
COPY services/ /etc/s6-overlay/s6-rc.d

# Copy crontab
COPY crontab /etc/crontab

ENTRYPOINT ["/init"]
